name: bank-app-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: simple_bank
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        echo "DB_DRIVER=postgres" > app.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> app.env
        echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> app.env
        echo "DB_SOURCE=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5433/simple_bank?sslmode=disable" >> app.env
        echo "SERVER_ADDRESS=0.0.0.0:8080" >> app.env

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Run DB migrations
      run: |
        set -a
        source app.env
        set +a
        make migrateup

    - name: Test
      run: make test
